npwoods/bletchmame

.github/workflows/main.yml, CMakeLists.txt, bletchmame.wxs, src/dialogs/inputs.cpp, src/dialogs/inputs.h, src/dialogs/paths.cpp, src/iconloader.h, src/prefs.h, src/tests/client_test.cpp, src/tests/dialogs/inputs_test.cpp, src/tests/dialogs/paths_test.cpp, src/tests/info_builder_test.cpp, src/tests/mameversion_test.cpp, src/tests/prefs_test.cpp, src/tests/runmachinetask_test.cpp, src/tests/softwarelist_test.cpp, src/tests/test.cpp, src/tests/test.h, src/tests/utility_test.cpp, src/utility.h, version.py
Also:
- Using CMake
- CI done on GitHub actions
- Acceptance tests
=> Ported BletchMAME to Qt

.gitignore, CMakeLists.txt, src/dialogs/about.h, src/dialogs/choosesw.h, src/dialogs/paths.cpp, src/dialogs/paths.h, src/mainwindow.cpp, src/prefs.cpp, src/runmachinetask.cpp, src/tests/prefs_test.cpp, src/tests/test.h
With this set of commits I'm able to build and run BletchMAME on Linux successfully.
=> multi platform fixes and initial Linux support

src/info_builder.cpp, src/prefs.cpp, src/profile.cpp, src/softwarelist.cpp, src/status.cpp, src/tests/xmlparser_test.cpp, src/xmlparser.cpp, src/xmlparser.h
=> Miscellaneous hygiene changes

lib/quazip/JlCompress.cpp, lib/quazip/quazipdir.cpp, lib/quazip/quazipfileinfo.cpp
Features that are not supported at all in Qt 6.0
=> Fixed some Quazip usage of deprecated Qt features

plugins/worker_ui/init.lua, src/bindata.h, src/info.cpp, src/info.h, src/info_builder.cpp, src/info_builder.h, src/machinelistitemmodel.cpp, src/machinelistitemmodel.h, src/mainwindow.cpp, src/status.cpp, src/status.h, src/tests/info_test.cpp
These are infrastructural changes in preparation for support for a slots dialog, which will be usable with MAME 0.227 and above.
=> Augmented the Info DB and Status facilities with slot and image format information

CMakeLists.txt, plugins/worker_ui/init.lua, src/mainwindow.cpp, src/mainwindow.h, src/profile.cpp, src/profile.h, src/profilelistitemmodel.cpp, src/profilelistitemmodel.h, src/runmachinetask.cpp, src/runmachinetask.h, src/sessionbehavior.cpp, src/sessionbehavior.h
This is not well tested - need to kick the tires some more
=> Profiles are now aware of slots and will now record changes in slots at runtime

.github/workflows/windows.yml, plugins/worker_ui/init.lua, src/mameworkercontroller.cpp, src/mameworkercontroller.h
MAME 0.227 has big LUA changes, so its worth it to "bracket" these changes
=> Start testing against MAME 0.226/0.227; stop testing against 0.225

plugins/worker_ui/init.lua, src/tests/mamerunner.cpp, src/tests/scripts/input.xml, src/tests/scripts/profiler.xml, src/tests/scripts/recording.xml, src/tests/scripts/simple.xml, src/tests/scripts/snap.xml, src/tests/scripts/state.xml, test_mame_interactions.sh
This should speed up the automated test runs
=> Proper sleep behavior during MAME interaction tests

.github/workflows/windows.yml
=> Setting up MSYS2 with 'release: false', to support automatic caching 

src/info.cpp, src/info_builder.cpp, src/info_builder.h, src/listxmltask.cpp, src/mainwindow.cpp, src/prefs.cpp, src/prefs.h, src/softwarelist.cpp, src/softwarelist.h, src/tests/prefs_test.cpp, src/tests/resources.qrc, src/tests/resources/prefs.xml, src/tests/softwarelist_test.cpp, src/utility.h, src/xmlparser.cpp, src/xmlparser.h
* Cleaned up `src/tests/prefs_test.cpp` (moved the test data to a resource, less OS-specific conditionals)
* Removed unnecessary usage of `QDataStream`
* Eliminated `wxFileExists()`
=> Miscellaneous hygienic changes

src/info_builder.cpp, src/info_builder.h, src/prefs.cpp, src/profile.cpp, src/softwarelist.cpp, src/status.cpp, src/tests/mamerunner.cpp, src/tests/xmlparser_test.cpp, src/xmlparser.cpp, src/xmlparser.h
- Greater use of std::optional
- Addition of radix overrides
=> Overhaul of src/xmlparser.[cpp|h]

src/info.cpp, src/info.h, src/info_builder.cpp, src/info_builder.h
=> Changed info::machine::rom_of() and info::machine::clone_of() to use machine indexes internally

src/mainwindow.cpp, src/mainwindow.h, src/mainwindow.ui, src/runmachinetask.cpp, src/runmachinetask.h
Trying to lay the foundation for support for platforms other than Windows
=> Various cleanups to the MAME integration

.github/workflows/windows_msvc2019.yml, scripts/bletchmame_build_msvc2019.sh, scripts/expat_build_msvc2019.sh, scripts/quazip_build_msvc2019.sh, scripts/zlib_build_msvc2019.sh
Also made a number of the MSVC 2019 build scripts support Debug and Release builds
=> Added a GitHub workflow for MSVC 2019 under Windows

README.md, src/tests/info_test.cpp, src/tests/test.cpp, src/tests/test.h, src/tests/xmlparser_test.cpp, src/xmlparser.cpp
=> Fixed an issue in Info XML parsing caused by inappropriately relying on the current locale's rules

src/dialogs/console.cpp, src/dialogs/console.h, src/dialogs/inputs.h, src/info_builder.cpp, src/mainwindow.cpp, src/mainwindow.h, src/prefs.h, src/tableviewmanager.cpp, src/xmlparser.cpp
=> More miscellaneous cleanups

CMakeLists.txt, src/dialogs/paths.cpp, src/dialogs/paths.h, src/dialogs/pathslistviewmodel.cpp, src/dialogs/pathslistviewmodel.h, src/tests/dialogs/pathslistviewmodel_test.cpp
=> Extracted the Paths Dialog's list view model into a separate module

src/iconloader.cpp, src/iconloader.h, src/machinelistitemmodel.cpp, src/machinelistitemmodel.h, src/mainpanel.cpp, src/prefs.cpp, src/tests/machinelistitemmodel_test.cpp, src/tests/utility_test.cpp, src/utility.h
Trying to broaden its usage for more than machine icons
=> Refactor of IconLoader and associated code

src/dialogs/choosesw.cpp, src/dialogs/confdevmodel.cpp, src/mainpanel.cpp, src/profile.cpp, src/sessionbehavior.cpp, src/softwarelist.cpp, src/softwarelist.h, src/softwarelistitemmodel.cpp
- private members
- accessors
- default ctors
=> Made software_list::software and software_list::part behave more like classes 

src/dialogs/paths.cpp, src/dialogs/paths.h, src/mainpanel.cpp, src/mainpanel.h, src/mainwindow.cpp, src/prefs.cpp, src/prefs.h
Made a QObject, using Qt facilities to propagate global path changes
=> Refactored Preferences

CMakeLists.txt, src/auditablelistitemmodel.h, src/auditcursor.cpp, src/auditcursor.h, src/machinelistitemmodel.cpp, src/machinelistitemmodel.h, src/mainpanel.cpp, src/mainpanel.h, src/mainwindow.cpp, src/mainwindow.h, src/prefs.cpp, src/prefs.h, src/softwarelistitemmodel.cpp, src/softwarelistitemmodel.h, src/tests/auditcursor_test.cpp
MachineAuditCursor is gone now and AuditCursor piggy backs off of the list item models
=> Overhauled how AuditCursor worked

README.md, src/dialogs/paths.cpp, src/dialogs/paths.h, src/dialogs/pathslistviewmodel.cpp, src/dialogs/pathslistviewmodel.h, src/tests/dialogs/paths_test.cpp
Also did a healthy refactoring of the paths dialog code, added more unit tests
=> Fixed a bug that could cause switching between paths in the paths dialog to not persist changes

README.md, src/hash.cpp
- Fixed a bug in hashing
- Updated README.md to reflect Davide Cavalca's changes
=> Minor changes

src/dialogs/importmameini.ui
1. Dialog is now larger
2. Slight change of wording on instructions
3. Disabled selection
=> Cosmetic changes to the MAME.INI import dialog

CMakeLists.txt, src/dialogs/importmameini.cpp, src/dialogs/importmameini.h, src/importmameinijob.cpp, src/importmameinijob.h, src/tests/importmameinijob_test.cpp, src/tests/resources.qrc, src/tests/resources/testmameini.ini
1. Renamed "Augment" to "Supplement"
2. Fixed an issue pertaining to how imported paths were compared with existing paths
3. Unit tests
=> Various import MAME.INI improvements

README.md, plugins/worker_ui/init.lua, src/tests/scripts/hard_reset.xml, src/tests/scripts/soft_reset.xml
=> Fixed an issue that caused resets to incorrectly pause the emulation

CMakeLists.txt, src/dialogs/confdev.cpp, src/dialogs/confdev.h, src/filedlgs.cpp, src/filedlgs.h, src/mainwindow.cpp, src/mainwindow.h
Sanitized lots of holdovers from wxWidgets
=> General cleanup to how BletchMAME handles QFileDialogs

README.md, src/mainpanel.cpp, src/mainwindow.cpp, src/tests/utility_test.cpp, src/utility.cpp, src/utility.h
=> Default snap naChanging screenshots to default to the snapshot directory, and prompting with the machine name

CMakeLists.txt, plugins/worker_ui/init.lua, src/devstatusdisplay.cpp, src/devstatusdisplay.h, src/dialogs/confdev.cpp, src/dialogs/confdev.h, src/dialogs/confdevmodel.cpp, src/dialogs/confdevmodel.h, src/imagemenu.cpp, src/imagemenu.h, src/mainwindow.cpp, src/mainwindow.h
1. The icon is always present while the image is loaded
2. Right clicking brings up a context menu with similar to functionality exposed in the Configurable Devices dialog
=> More changes to the Device Status on the Status Bar

src/mainwindow.cpp, src/mainwindow.h, src/prefs.cpp, src/prefs.h, src/tests/prefs_test.cpp
The purpose of this is two-fold:
- Cut down on what is going on in MainWindow
- Facilitate unit testing
=> Moving placeInRecentDeviceFiles() logic to Preferences

src/auditqueue.cpp, src/bindata.h, src/dialogs/confdev.cpp, src/dialogs/confdevmodel.cpp, src/dialogs/console.cpp, src/dialogs/importmameini.cpp, src/dialogs/inputs.cpp, src/dialogs/switches.cpp, src/imagemenu.cpp, src/importmameinijob.cpp, src/info.cpp, src/machinefoldertreemodel.cpp, src/mainpanel.cpp, src/mainwindow.cpp, src/prefs.cpp, src/profile.cpp, src/softwarelist.cpp, src/status.cpp, src/taskdispatcher.cpp, src/tests/mamerunner.cpp
Needed to more or less rewrite bindata::view to accommodate this
=> Making use of C++20 ranges

.github/workflows/windows_msvc2019.yml, scripts/bletchmame_build_msvc.sh, scripts/qt6_retrieve.sh, scripts/quazip_build_msvc.sh, scripts/validate_dllimports.pl
In these cases, it was incorrectly hardcoding 6.1.2
=> Fixed option to specify Qt version on a few scripts

src/info_builder.cpp, src/info_builder.h, src/tests/info_builder_test.cpp, src/xmlparser.cpp, src/xmlparser.h
It already expected strings not contain NUL characters, so we've done some optimizations based around that assumption
=> Optimized info::database_builder::string_table::get()

src/info.cpp, src/info.h, src/info_builder.cpp, src/info_builder.h, src/listxmltask.cpp, src/listxmltask.h, src/tests/listxmltask_test.cpp, src/xmlparser.cpp, src/xmlparser.h
We were only using list_xml_exception, which was easily changed
=> Getting rid of exception usage

src/dialogs/choosesw.cpp, src/mainpanel.cpp, src/tableviewmanager.cpp, src/tableviewmanager.h
Also did a minor refactoring to `TableViewManager` setup so this problem won't come back
=> Fixed the default configuration for the machine source file and software list file columns

.github/workflows/linux.yml, .github/workflows/windows_msvc2019.yml, .github/workflows/windows_msys2.yml, CMakeLists.txt
This is possible now that lzma-c-sdk has been updated
=> Use CMake's find_package() to locate LZMA

CMakeLists.txt, src/importmameinijob.cpp, src/importmameinijob.h, src/tests/importmameinijob_test.cpp
...by replacing `QRegExp` with `QRegularExpression`
=> Eliminating usage of Qt Core5Compat module

.github/workflows/linux.yml, .github/workflows/windows_msvc2019.yml, CMakeLists.txt, src/hash.cpp, src/iniparser.cpp, src/iniparser.h
- 6.2.1, which we build Windows against
- 6.4.0, which is (currently) the latest
=> Changing Qt versions in CI

.github/workflows/windows_msvc2019.yml, CMakeLists.txt, src/devstatusdisplay.cpp, src/devstatusdisplay.h, src/tests/devstatusdisplay_test.cpp, src/tests/machinefoldertreemodel_test.cpp, src/tests/test.cpp, src/tests/test.h
This was broken when changing how we work with static Qt under MSYS2
=> Readding Qt:ICOPlugin when linking to Qt statically
